---
- hosts: db
  become: yes
  tasks:

  - name: create file
    copy: 
       src: /home/user01/file
       dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb
    yum: 
      name: mongodb-org
      state: present

  - name: start mongodb service
    service:
      name: mongod
      state: started
enabled: yes
